name: Build and Upload Marp Presentations on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  build-presentations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensures we have at least the previous commit for diffing

      - name: Find Changed Markdown Files in Content Directory
        id: changed-md
        run: |
          BASE_SHA="HEAD^"
          HEAD_SHA="HEAD"
          
          # Find changed files only in the content directory
          CHANGED_FILES=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" -- 'content/*.md' | tr '\n' ' ')
          echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV

      - name: Create Temporary Directory
        run: |
          mkdir -p temp_output
          chmod -R 777 temp_output  # Ensure write permissions
          echo "TEMP_DIR=temp_output" >> $GITHUB_ENV

      - name: Convert Markdown to HTML and PDF using Marp CLI
        if: env.CHANGED_FILES != ''
        run: |
          for file in $CHANGED_FILES; do
            RELATIVE_PATH="${file#content/}"
            OUTPUT_DIR="$TEMP_DIR/$(dirname "$RELATIVE_PATH")"
            mkdir -p "$OUTPUT_DIR"
            chmod -R 777 "$OUTPUT_DIR"  # Ensure write permissions
            
            # Run Marp CLI without specifying a user to avoid permission issues
            docker run --rm -v "$PWD:/workspace" -w /workspace ghcr.io/marp-team/marp-cli "$file" --output "$OUTPUT_DIR/$(basename "${file%.md}.html")"
            docker run --rm -v "$PWD:/workspace" -w /workspace ghcr.io/marp-team/marp-cli "$file" --output "$OUTPUT_DIR/$(basename "${file%.md}.pdf")"
          done

      - name: Upload Converted Files as Artifact
        if: env.CHANGED_FILES != ''
        uses: actions/upload-artifact@v4
        with:
          name: converted-presentations
          path: temp_output

  upload-to-google-drive:
    runs-on: ubuntu-latest
    needs: build-presentations

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Converted Files
        uses: actions/download-artifact@v4
        with:
          name: converted-presentations
          path: temp_output

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Create Google Drive Credentials File
        run: |
          echo '${{ secrets.GDRIVE_CREDENTIALS }}' > creds.json

      - name: Upload Converted Files to Google Drive
        run: |
          for file in $(find temp_output -type f); do
            RELATIVE_PATH="${file#temp_output/}"
            python google_drive_upload.py "$file" "1UcpTtlguwZa8xu3ac7yNy4mM8ALPmqf9:$RELATIVE_PATH"
          done
