
name: Publish HTML presentations from main to github pages.

on:
    workflow_dispatch:

jobs:
  build-presentations:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensures we have at least the previous commit for diffing

      - name: Create Publish Directory
        env:
          PUBLISH_DIR: ${{ vars.PUBLISH_DIR }}
        run: |
          echo "Creating publish directory..."
          mkdir -p $PUBLISH_DIR
          chmod -R 777 $PUBLISH_DIR  # Ensure write permissions

      - name: Set publish folder permissions
        env:
          PUBLISH_DIR: ${{ vars.PUBLISH_DIR }}
        run: |
          echo "Setting publish folder permissions..."
          chmod -R 777 $PUBLISH_DIR

      - name: Ensure content directory is writable
        run: |
          chmod -R 777 content

      - name: Convert Markdown to HTML using Marp CLI
        run: |
          docker run --rm -v "$PWD:/workspace" -w /workspace ghcr.io/marp-team/marp-cli --allow-local-files content --html

      - name: Copy converted HTML and assets to publish directory
        env:
          PUBLISH_DIR: ${{ vars.PUBLISH_DIR }}
        run: |
          cd content
          find . -type f -name "*.html" -exec cp --parents {} "$PUBLISH_DIR/" \;
          find . -type d -name "assets" -exec cp -r --parents {} "$PUBLISH_DIR/" \;

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Create index.html
        env:
          PUBLISH_DIR: ${{ vars.PUBLISH_DIR }}
        run: |
          echo "Creating index.html..."
          python3 build_index_page.py
          chmod  777 $PUBLISH_DIR/index.html
          echo "index.html created successfully."

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ vars.PUBLISH_DIR }}
