
name: Publish HTML presentations from main to github pages.

on:
    workflow_dispatch:

jobs:
  build-presentations:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/build-index-page-for-pages'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensures we have at least the previous commit for diffing

      - name: Create Publish Directory
        env:
          PUBLISH_DIR: ${{ vars.PUBLISH_DIR }}
        run: |
          echo "Creating publish directory..."
          mkdir -p $PUBLISH_DIR
          chmod -R 777 $PUBLISH_DIR  # Ensure write permissions

      - name: Copy assets directories to the publish directory
        env:
          PUBLISH_DIR: ${{ vars.PUBLISH_DIR }}
        run: |
          find content -type d -name "assets" | while read file; do
            assets_dir=${file#content/}
            echo "Copying assets directory: $assets_dir to $PUBLISH_DIR/$assets_dir"
            mkdir -p $PUBLISH_DIR/$assets_dir
            cp -r $file $PUBLISH_DIR/$assets_dir
          done

      - name: Set publish folder permissions
        env:
          PUBLISH_DIR: ${{ vars.PUBLISH_DIR }}
        run: |
          echo "Setting publish folder permissions..."
          chmod -R 777 $PUBLISH_DIR

      - name: Convert Markdown to HTML and PDF using Marp CLI
        env:
          PUBLISH_DIR: ${{ vars.PUBLISH_DIR }}
        run: |
          find content -type f -name "*.md" | while read file; do
            relative_path="${file#content/}"
            output_dir="$PUBLISH_DIR/$(dirname "$relative_path")"
            output_path_html="$output_dir/$(basename "${file%.md}.html")"

            # Run Marp CLI without specifying a user to avoid permission issues
            docker run --rm -v "$PWD:/workspace" -w /workspace ghcr.io/marp-team/marp-cli --allow-local-files "$file" --output "$output_path_html" --html
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Create index.html
        env:
          PUBLISH_DIR: ${{ vars.PUBLISH_DIR }}
        run: |
          echo "Creating index.html..."
          python3 build_index_page.py
          chmod  777 $PUBLISH_DIR/index.html
          echo "index.html created successfully."

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/build-index-page-for-pages'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ vars.PUBLISH_DIR }}
